#!/bin/sh

#SBATCH -N 1
#SBATCH -p RM
#SBATCH --ntasks-per-node=128
#SBATCH --job-name=ref3c
#SBATCH --output=ref3c%j.out
#SBATCH --time=72:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kuanrenq@andrew.cmu.edu

mkdir ../io3D_ref3/
mkdir ../io3D_ref3/outputs/

module load openmpi/5.0.3-gcc13.2.1
/ocean/projects/eng170006p/ussqww/petsc/arch-linux-c-opt/bin/mpiexec -np 128 ./3DNG --numNeuron=1 --end_iter=500000 --solver=snes --path_in=../io3D_ref3/ --restart=yes | tee -a ../io3D_ref3/log_continue.txt

#-- exit
#
