#!/bin/sh

#SBATCH -N 1
#SBATCH -p RM
#SBATCH --ntasks-per-node=128
#SBATCH --job-name=THBNG
#SBATCH --output=THBNG%j.out
#SBATCH --time=8:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kuanrenq@andrew.cmu.edu

mkdir ../io3D/
mkdir ../io3D/outputs/

module load openmpi/5.0.3-gcc13.2.1
/ocean/projects/eng170006p/ussqww/petsc/arch-linux-c-opt/bin/mpiexec -np 128 ./3DNG 1 350000 snes ../io3D/

#-- exit
#
