#!/bin/sh

#SBATCH -N 1
#SBATCH -p RM
#SBATCH --ntasks-per-node=128
#SBATCH --job-name=3dng
#SBATCH --output=3dng%j.out
#SBATCH --time=48:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user=kuanrenq@andrew.cmu.edu

mkdir ../io3D/
mkdir ../io3D/outputs/

module load openmpi/5.0.3-gcc13.2.1
/ocean/projects/eng170006p/ussqww/petsc/arch-linux-c-opt/bin/mpiexec -np 128 ./3DNG --numNeuron=1 --end_iter=500000 --solver=snes --path_in=../io3D/ --restart=no | tee -a ../io3D/log.txt

#-- exit
#
